### ISSUE TITLE
Creating a rock

### ISSUE THREAD

**Issue by lammermann** [brimworks/lua-zip#2]
It would be great to publish this lib at [luarocks](http://www.luarocks.org/).

It's the only zip binding for lua with write support I know and I would like to add it as a dependency for [lunamark](http://jgm.github.com/lunamark/) (for opendocument output).

Are there any plans to do this?

**Comment by MisterDA** [comment]
There is a rock now, but it is only a development rock.
It would be nice to release (possibly after fixing #8) the library as a stable version and provide a new rock. For now users are required to use this `luarocks install --server=http://luarocks.org/dev lua-zip` rather than `luarocks install lua-zip` and other packages that may depend on lua-zip can't simply add lua-zip as a dependency because it requires manual interaction from the user (copy-pasting the long comment).
